### ISSUE TITLE
«"GPBMetadata\Google\Cloud\Vision\V1\ImageAnnotator" not found in vendor/google/cloud-vision/src/V1/Image.php:56»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/color#5]
```
#0 vendor\google\cloud-vision\src\VisionHelpersTrait.php(101): Google\Cloud\Vision\V1\Image->__construct()
#1 vendor\google\cloud-vision\src\V1\ImageAnnotatorClient.php(76): Google\Cloud\Vision\V1\ImageAnnotatorClient->createImageHelper('Google\\Cloud\\Vi...', 'Google\\Cloud\\Vi...', '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...')
#2 vendor\google\cloud-vision\src\V1\ImageAnnotatorClient.php(111): Google\Cloud\Vision\V1\ImageAnnotatorClient->createImageObject('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...')
#3 vendor\google\cloud-vision\src\V1\ImageAnnotatorClient.php(556): Google\Cloud\Vision\V1\ImageAnnotatorClient->annotateImage('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Array, Array)
#4 vendor\google\cloud-vision\src\V1\ImageAnnotatorClient.php(387): Google\Cloud\Vision\V1\ImageAnnotatorClient->annotateSingleFeature('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', 7, Array)
#5 vendor\mage2pro\color\Image.php(61): Google\Cloud\Vision\V1\ImageAnnotatorClient->imagePropertiesDetection('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...')
#6 vendor\mage2pro\core\Core\lib\cache\dfc.php(78): Dfe\Color\Image->Dfe\Color\{closure}()
#7 vendor\mage2pro\color\Image.php(69): dfc(Object(Dfe\Color\Image), Object(Closure))
#8 vendor\mage2pro\color\Image.php(27): Dfe\Color\Image->dominant()
#9 vendor\mage2pro\core\Core\lib\cache\dfc.php(78): Dfe\Color\Image->Dfe\Color\{closure}()
#10 vendor\mage2pro\color\Image.php(38): dfc(Object(Dfe\Color\Image), Object(Closure))
#11 vendor\mage2pro\color\Observer\ProductSaveBefore.php(33): Dfe\Color\Image->probabilities()
#12 lib\internal\Magento\Framework\Event\Invoker\InvokerDefault.php(88): Dfe\Color\Observer\ProductSaveBefore->execute(Object(Magento\Framework\Event\Observer))
#13 lib\internal\Magento\Framework\Event\Invoker\InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Dfe\Color\Observer\ProductSaveBefore), Object(Magento\Framework\Event\Observer))
#14 lib\internal\Magento\Framework\Event\Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#15 generated\code\Magento\Framework\Event\Manager\Proxy.php(105): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
#16 lib\internal\Magento\Framework\Model\AbstractModel.php(711): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)
#17 app\code\Magento\Catalog\Model\AbstractModel.php(383): Magento\Framework\Model\AbstractModel->beforeSave()
#18 app\code\Magento\Catalog\Model\Product.php(925): Magento\Catalog\Model\AbstractModel->beforeSave()
#19 lib\internal\Magento\Framework\EntityManager\Observer\BeforeEntitySave.php(34): Magento\Catalog\Model\Product->beforeSave()
#20 lib\internal\Magento\Framework\Event\Invoker\InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\BeforeEntitySave->execute(Object(Magento\Framework\Event\Observer))
#21 lib\internal\Magento\Framework\Event\Invoker\InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\BeforeEntitySave), Object(Magento\Framework\Event\Observer))
#22 lib\internal\Magento\Framework\Event\Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#23 generated\code\Magento\Framework\Event\Manager\Proxy.php(105): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#24 lib\internal\Magento\Framework\EntityManager\EventManager.php(50): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#25 lib\internal\Magento\Framework\EntityManager\Operation\Create.php(116): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_before', Array)
#26 lib\internal\Magento\Framework\EntityManager\EntityManager.php(106): Magento\Framework\EntityManager\Operation\Create->execute(Object(Magento\Catalog\Model\Product), Array)
#27 app\code\Magento\Catalog\Model\ResourceModel\Product.php(779): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product))
#28 lib\internal\Magento\Framework\Model\AbstractModel.php(664): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product))
#29 app\code\Magento\Catalog\Controller\Adminhtml\Product\Save.php(143): Magento\Framework\Model\AbstractModel->save()
#30 lib\internal\Magento\Framework\App\Action\Action.php(111): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#31 app\code\Magento\Backend\App\AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#32 lib\internal\Magento\Framework\App\FrontController.php(245): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#33 lib\internal\Magento\Framework\App\FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Catalog\Controller\Adminhtml\Product\Save), Object(Magento\Framework\App\Request\Http))
#34 lib\internal\Magento\Framework\App\FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Adminhtml\Product\Save))
#35 lib\internal\Magento\Framework\App\Http.php(116): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#36 lib\internal\Magento\Framework\App\Bootstrap.php(264): Magento\Framework\App\Http->launch()
#37 pub\index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
```

**Comment by dmitrii-fediuk** [comment]
It is because the `GPBMetadata\Google\Cloud\Vision\V1\ImageAnnotator` class since **1.3.0** contains binary data which PHP (I use **8.2.9**) does not handle correctly:
https://github.com/googleapis/google-cloud-php-vision/blob/v1.2.0/metadata/V1/ImageAnnotator.php
https://github.com/googleapis/google-cloud-php-vision/blob/v1.3.0/metadata/V1/ImageAnnotator.php		
![2023-08-01--23-32-08](https://github.com/mage2pro/color/assets/83204/2deab92d-f181-4b75-b7a8-2dbc37704cbf)
